apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-node-js
  template:
    metadata:
      labels:
        app: k8s-node-js
    spec:
      containers:
      - name: k8s-node-js
        image: sudipdas2001/k8s-node-js
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
